{

addBook(new Book("Titolo","Autore",2026));
addBook(new Book("1984","George Orwell",2026));
addBook(new Book("101 cose da fare a Roma almeno una volta nella vita","Ilaria Beltramme",2026));
addBook(new Book("I Sonetti","Trilussa",2026));
addBook(new Book("101 perchè sulla storia di Roma che non puoi non sapere","Ilaria Beltramme",2026));
addBook(new Book("500 ricette di piatti unici","Laura Rangoni",2026));
addBook(new Book("A cavallo della luna. La storia di Pino","Claudio Giorlandino",2026));
addBook(new Book("Il Fascismo Eterno","Umberto Eco",2026));
addBook(new Book("A Classical Education: The Stuff You Wish You'd Been Taught At School","Caroline Taggart",2026));
addBook(new Book("A Good Woman","Danielle Steel",2026));
addBook(new Book("A Thousand Splendid Suns","Khaled Hosseini",2026));
addBook(new Book("A Touch of Love","Jonathan Coe",2026));
addBook(new Book("Il Giudizio di Salomone","Patrick Weiller",2026));
addBook(new Book("A Word in Your Shell-Like: 6","Nigel Rees",2026));
addBook(new Book("Pensieri sulla democrazia in Europa","Giuseppe Mazzini",2026));
addBook(new Book("Carlo Lucarelli","Andrea Camilleri",2026));
addBook(new Book("Ad occhi chiusi","Gianrico Carofiglio",2026));
addBook(new Book("Addio","Agatha Christie",2026));
addBook(new Book("Marco Andrea De","Davide Vasta",2026));
addBook(new Book("Andrea Rotondo","Marco Feo",2026));
addBook(new Book("Adobe Photoshop CS4. Lavorare con creativit? su fotografie e immagini digitali","vuoto",2026));
addBook(new Book("Adobe Photoshop CS5. Lavorare con creativit? su fotografie e immagini digitali","Edimatica",2026));
addBook(new Book("Domenico Belardo","Nunzio Trotta",2026));
addBook(new Book("Advanced Grammar in Use With CD ROM","Martin Hewings",2026));
addBook(new Book("Gerald Hinde","Richard Du Toit",2026));
addBook(new Book("AJAX - Guida per lo sviluppatore","vuoto",2026));
addBook(new Book("Al di la' del principio del piacere","Sigmund Freud",2026));
addBook(new Book("Alghero","Antonio Nughes",2026));
addBook(new Book("Alice's Adventures in Wonderland (Oxford Bookworms Library)","Bassett",2026));
addBook(new Book("Alive in Africa: My Journeys on Foot in the Sahara","William F. Wheeler",2026));
addBook(new Book("G. Hirzer","Wilbur Smith",2026));
addBook(new Book("Ama l'italiano. Segreti e meraviglie della lingua più bella","Annalisa Andreoni",2026));
addBook(new Book("Amore e sesso nell'antica Roma","Alberto Angela",2026));
addBook(new Book("And the Mountains Echoed","Khaled Hosseini",2026));
addBook(new Book("Angeli E Demoni","Dan Brown",2026));
addBook(new Book("M. C. Capanna","Andrea Carandini",2026));
addBook(new Book("Anima carnale","Alberto Bevilacqua",2026));
addBook(new Book("Malcolm Bradbury","George Orwell",2026));
addBook(new Book("Finzioni","Jorge Luis Borges",2026));
addBook(new Book("Bianca Ceva","Publio Cornelio Tacito",2026));
addBook(new Book("Annus horribilis","Giorgio Bocca",2026));
addBook(new Book("The Camera (Ansel Adams Photography","Ansel Adams",2026));
addBook(new Book("Apache Pocket Reference","vuoto",2026));
addBook(new Book("David Lane","Hugh E. Williams",2026));
addBook(new Book("Arditi contro. I primi anni di piombo a Roma 1919-1923","Andrea Augello",2026));
addBook(new Book("P. Faccia","Kelly M. Greenhill",2026));
addBook(new Book("Ars moriendi. Indagine a Pompei","Danila Comastri Montanari",2026));
addBook(new Book("ASP.NET 2.0","vuoto",2026));
addBook(new Book("Atlas (World Atlas)","Dk",2026));
addBook(new Book("Atonement","Ian McEwan",2026));
addBook(new Book("Australia and New Zealand: Stage 3 (Oxford Bookworms Library","Christine Lindop",2026));
addBook(new Book("L'Aleph","Jorge Luis Borges",2026));
addBook(new Book("Luigi Santapaga","Matteo Trasi",2026));
addBook(new Book("Bassa risoluzione","Massimo Mantellini",2026));
addBook(new Book("Norman Arlott","J. G. Williams",2026));
addBook(new Book("Black & Blue","Ian Rankin",2026));
addBook(new Book("Blender. La guida. Con CD-ROM.","Carsten. Wartmann",2026));
addBook(new Book("Margaret Atwood","Aldous Huxley",2026));
addBook(new Book("Francois Caen","Christopher Negus",2026));
addBook(new Book("C - Corso completo di programmazione","Deitel & Deitel",2026));
addBook(new Book("C# 2005 Guida per lo sviluppatore","vuoto",2026));
addBook(new Book("Paul J. Deitel","Harvey M. Deitel",2026));
addBook(new Book("Paul J. Deitel","Harvey M. Deitel",2026));
addBook(new Book("C. M. Valentinetti","Jorge Amado",2026));
addBook(new Book("Cacciatori di diamanti","Wilbur Smith",2026));
addBook(new Book("Caffè amaro","Simonetta Agnello Hornby",2026));
addBook(new Book("Barbara Thomas","Louise Hashemi",2026));
addBook(new Book("Cambridge Idioms Dictionary","vuoto",2026));
addBook(new Book("Camminando. Incontri di un viandante","Pino Cacucci",2026));
addBook(new Book("Canterville Ghost (Oxford Bookworms)","Bassett",2026));
addBook(new Book("Caramba!","Nina M. Mart?nez",2026));
addBook(new Book("Carpe diem. Le più belle citazioni latine","aa.vv.",2026));
addBook(new Book("Carta Bianca","Lucarelli Carlo",2026));
addBook(new Book("Cave canem","Danila Comastri Montanari",2026));
addBook(new Book("Cent'anni di solitudine","Gabriel Garcia Marquez",2026));
addBook(new Book("Herbert Robbins","Richard Courant",2026));
addBook(new Book("Che la festa Cominci","Niccolo Ammaniti",2026));
addBook(new Book("Circolo Chiuso","Jonathan Coe",2026));
addBook(new Book("CLAIRE","Christian Jacq",2026));
addBook(new Book("Colosseo-Palatino-Foro romano-Domus Aurea. Ediz. italiana","aa vv",2026));
addBook(new Book("Come disegnare i paesaggi. Tutte le fasi per realizzare a matita ogni singolo elemento del paesaggio: alberi","Ferdinand Petrie",2026));
addBook(new Book("Come disegnare la figura vestita. Per riprodurre nel migliore dei modi pieghe e drappeggi","Hogart Burne",2026));
addBook(new Book("Come diventare vivi. Un vademecum per lettori selvaggi","Giuseppe Montesano",2026));
addBook(new Book("Come Il Mare","Wilbur Smith",2026));
addBook(new Book("Contro il fascismo-Un anno di dominazione fascista","Giacomo Matteotti",2026));
addBook(new Book("Contro venti e maree. Idee sull'Europa e sull'Italia. Conversazione con Sébastien Millard","Enrico Letta",2026));
addBook(new Book("Gary. Cornell","Cay S. Horstmann",2026));
addBook(new Book("Gary Cornell","Cay S. Horstmann",2026));
addBook(new Book("Cosi parlo Bellavista.","Luciano DeCrescenzo",2026));
addBook(new Book("Costruire applicazioni cpn Access (versioni 97 e 2000)","Mike Davis",2026));
addBook(new Book("Costruire siti dinamici con Joomla! 1.5","Roberto Chimenti",2026));
addBook(new Book("Creare blog e siti web con WordPress","Tiziano Fogliata",2026));
addBook(new Book("Cromorama. Come il colore ha cambiato il nostro sguardo","Riccardo Falcinelli",2026));
addBook(new Book("Jason King","M.J. Easton",2026));
addBook(new Book("Crypto","Dan Brown",2026));
addBook(new Book("CSS","Gianluca Troiani",2026));
addBook(new Book("Cubase 4. Musica digitale. Guida pratica per diventare musicisti digitali. Con CD-ROM","Fabio Fracas",2026));
addBook(new Book("Cui prodest?","Danila Comastri Montanari",2026));
addBook(new Book("Cuore scuro","Paolo Bertetto",2026));
addBook(new Book("Curiosità romane","Costantino Maes",2026));
addBook(new Book("Dark Flight","Lin Anderson",2026));
addBook(new Book("Dark Heart of Italy","Tobias Jones",2026));
addBook(new Book("Data mining. Modelli informatici","Paolo Giudici",2026));
addBook(new Book("Stefano Rizzi","Matteo Golfarelli",2026));
addBook(new Book("David Copperfield (Oxford Bookworms Library Classics)","Bassett",2026));
addBook(new Book("De rerum natura. Testo latino a fronte","Tito Lucrezio Caro",2026));
addBook(new Book("Deadly Code","Lin Anderson",2026));
addBook(new Book("Decamerino. Novelle dietro le quinte","Gigi Proietti",2026));
addBook(new Book("R. Marrone","Giovanni Boccaccio",2026));
addBook(new Book("DELPHI 6","vuoto",2026));
addBook(new Book("Dieci anni di illusioni. Storia del Sessantotto","Michele Brambilla",2026));
addBook(new Book("Dimore Eterne","Alberto Siliotti",2026));
addBook(new Book("Dizionario d'uso dei phrasal verbs. Inglese-italiano. Dizionario completo dei verbi frasali inglesi","Fernando Picchi",2026));
addBook(new Book("Dizionario romanesco","Fernando Ravaro",2026));
addBook(new Book("Donna per caso","Jonathan Coe",2026));
addBook(new Book("Dopo la notte","Elie Wiesel",2026));
addBook(new Book("Dove Finisce L'arcobaleno - Quattro Destini Uniti in Un Sogno Di Spreanza E Liberta","Wilbur Smith",2026));
addBook(new Book("Rosemary Border","Robert Louis Stevenson",2026));
addBook(new Book("Driftnet (Rhona MacLeod)","Lin Anderson",2026));
addBook(new Book("Dura lex","Danila Comastri Montanari",2026));
addBook(new Book("E so' problemi","Federico Palmaroli",2026));
addBook(new Book("Easy Kill","Lin Anderson",2026));
addBook(new Book("Easy Oracle PHP: Create Dynamic Web Pages with Oracle Data (Easy Oracle Series)","Mladen Gogala",2026));
addBook(new Book("Eclisse del Dio unico","Ferruccio Parazzoli",2026));
addBook(new Book("Donald Reid","Rob Humphreys",2026));
addBook(new Book("Egitto. Popolo divinità faraoni","Rose-Marie Hagen",2026));
addBook(new Book("Eichmann and the Holocaust","Hannah Arendt",2026));
addBook(new Book("Emmaus","Alessandro Baricco",2026));
addBook(new Book("Felicity O'Dell","Michael McCarthy",2026));
addBook(new Book("Esercizi di memoria","Andrea Camilleri",2026));
addBook(new Book("Espressioni regolari","Marco Beri",2026));
addBook(new Book("Estetica della scorreggia. Appunti per una buona applicazione della tromba di culo ad uso dei cultori","Tony Siluro Ventilatio",2026));
addBook(new Book("Etica","Baruch Spinoza",2026));
addBook(new Book("Excel e Office VBA. La guida completa. Con CD-ROM","Gianni Giaccaglini",2026));
addBook(new Book("Fascio e martello. Viaggio per le città del duce","Antonio Pennacchi",2026));
addBook(new Book("Richard Acklam","Judith Wilson",2026));
addBook(new Book("Judith Wilson","Sally Burgess",2026));
addBook(new Book("Field Guide to Common Trees and Shrubs of East Africa","Najma Dharani",2026));
addBook(new Book("Figli Del Nilo","Wilbur Smith",2026));
addBook(new Book("FileMaker PRO - Guida Pratica","Roberto Celano",2026));
addBook(new Book("Final Cut (Rhona MacLeod)","Lin Anderson",2026));
addBook(new Book("Final Cut Pro per i professionisti","Alex C. Raccuglia",2026));
addBook(new Book("Final Cut studio 2. Con CD-ROM","Massimiliano D'Andrea",2026));
addBook(new Book("Five Comic One-Act Plays (Dover Thrift Editions)","A. P. Chekhov",2026));
addBook(new Book("Snow Dowd","Robert Reinhardt",2026));
addBook(new Book("Fondamentalismi. I diversi volti dell'intransigenza religiosa","Massimo Introvigne",2026));
addBook(new Book("Fotografia. Teoria e pratica della Reflex","Giulio Forti",2026));
addBook(new Book("Frankenstein. Con CD Audio. Con CD-ROM. Con espansione online","Mary Shelley",2026));
addBook(new Book("I. Annoni","Michael Wolff",2026));
addBook(new Book("Gabriela","Jorge Amado",2026));
addBook(new Book("Gallia est","Danila Comastri Montanari",2026));
addBook(new Book("Valeria Manferto","De Fabianis",2026));
addBook(new Book("Giallo antico. Come si scrive un poliziesco storico","Danila Comastri Montanari",2026));
addBook(new Book("GIMP","vuoto",2026));
addBook(new Book("Gli africani siamo noi. Alle origini dell'uomo","Guido Barbujani",2026));
addBook(new Book("Gli eredi dell'eden","Wilbur Smith",2026));
addBook(new Book("C. Lionetti","Nicolas d'Estienne D'Orves",2026));
addBook(new Book("P. Pierri","Sandro Pertini",2026));
addBook(new Book("GLOBUS Enciclopedia dei paesi e degli itinerari: Stati Uniti e Canada","vuoto",2026));
addBook(new Book("Gomorra. Viaggio nell'impero economico e nel sogno di dominio della camorra","Roberto Saviano",2026));
addBook(new Book("Grammatica italiana per tutti","Elisabetta Perini",2026));
addBook(new Book("Gramsci. Una nuova biografia","Angelo D'Orsi",2026));
addBook(new Book("La Natura Esposta","Erri De Luca",2026));
addBook(new Book("Gran circo Taddei e altre storie di Vigàta","Andrea Camilleri",2026));
addBook(new Book("Guida alla cucina etrusca. Cibi e divertimenti in Etruria","Clotilde Vesco",2026));
addBook(new Book("Harry Potter and the Deathly Hallows","J.K. Rowling",2026));
addBook(new Book("Harry Potter e la maledizione dell'erede","Joanne K. Rowling",2026));
addBook(new Book("Helmut Newton","June Newton",2026));
addBook(new Book("Ho finalmente capito l'Italia. Piccolo trattato ad uso degli stranieri (e degli italiani)","Philippe Daverio",2026));
addBook(new Book("I campi del Duce. L'internamento civile nell'Italia fascista (1940-1943)","Carlo S. Capogreco",2026));
addBook(new Book("I castelli romani. Un viaggio nello spazio e nel tempo","Renato Mammucari",2026));
addBook(new Book("L. Bises","Ian Sidaway",2026));
addBook(new Book("G. Arduino","Glenn Cooper",2026));
addBook(new Book("Domenico Dodaro","Marco Consentino",2026));
addBook(new Book("Janice Kirk","Gina Buonaguro",2026));
addBook(new Book("I segreti del Codice da Vinci. Guida non autorizzata a fatti","Simon Cox",2026));
addBook(new Book("I segreti dell'acrilico","Gill Barron",2026));
addBook(new Book("I Segreti di Londra","Corrado Augias",2026));
addBook(new Book("I segreti tecnologici degli antichi romani","Giulia Fiore Coltellacci",2026));
addBook(new Book("I sensi incantati","Alberto Bevilacqua",2026));
addBook(new Book("I sogni di Andrea Camilleri","Andrea Camilleri",2026));
addBook(new Book("I sogni di mio padre. Un racconto sulla razza e l'eredit","Barack Obama",2026));
addBook(new Book("Maria Sole Croce","Alessandro Bongiovanni",2026));
addBook(new Book("I tre giorni di Pompei: 23-25 ottobre 79 d. C. Ora per ora","Alberto Angela",2026));
addBook(new Book("I Used to Know That: A Classical Education","Caroline Taggart",2026));
addBook(new Book("I Used to Know That: English","Patrick Scrivenor",2026));
addBook(new Book("I Used to Know That: General Science","Marianne Taylor",2026));
addBook(new Book("I vangeli apocrifi","M. Craveri",2026));
addBook(new Book("Iacobus","Matilde Asensi",2026));
addBook(new Book("Il Broglio","vuoto",2026));
addBook(new Book("Il Cacciatore Di Aquiloni","Khaled Hosseini",2026));
addBook(new Book("R. Zuppet","Glenn Cooper",2026));
addBook(new Book("Il campo del vasaio","Andrea Camilleri",2026));
addBook(new Book("Il cimitero di Praga","Umberto Eco",2026));
addBook(new Book("Gatti molto speciali","Doris Lessing",2026));
addBook(new Book("M. Zanarini","Daniel Estulin",2026));
addBook(new Book("Il Codice Da Vinci","Dan Brown",2026));
addBook(new Book("Il colore del sole","Andrea Camilleri",2026));
addBook(new Book("Il Corano","aa.vv.",2026));
addBook(new Book("Il destino del cacciatore","Wilbur Smith",2026));
addBook(new Book("Il destino del leone","Wilbur Smith",2026));
addBook(new Book("Il diavolo","Andrea Camilleri",2026));
addBook(new Book("R. Rambelli","Wilbur Smith",2026));
addBook(new Book("Il diritto di avere diritti","Stefano Rodot",2026));
addBook(new Book("Il disagio della libertà. Perchè agli italiani piace avere un padrone","Corrado Augias",2026));
addBook(new Book("R. Cravero","Siegfried Lenz",2026));
addBook(new Book("Il Cuore dello Yoga","T.K.V. Desikachar",2026));
addBook(new Book("Il Dottor Zivago","Boris Pasternak",2026));
addBook(new Book("Il Faraone Nero","Christian Jacq",2026));
addBook(new Book("Il farmacista di Auschwitz","Dieter Schlesak",2026));
addBook(new Book("Il Figlio Della Luce (Italian Edition)","Christian Jacq",2026));
addBook(new Book("Il Gattopardo","Giuseppe Tomasi di Lampedusa",2026));
addBook(new Book("Il giardino dei Finzi-Contini","Giorgio Bassani",2026));
addBook(new Book("Il gioco degli specchi","Andrea Camilleri",2026));
addBook(new Book("Il gioco dell'angelo","Carlos Ruiz Zafon",2026));
addBook(new Book("Il giro di boa","Andrea Camilleri",2026));
addBook(new Book("I.C.J. Galbraith","Philip Whitfield",2026));
addBook(new Book("Il grande libro del rock (e non solo). Musica per tutti i giorni dell'anno","Massimo Cotto",2026));
addBook(new Book("Boccamurata","Simonetta Agnello Hornby",2026));
addBook(new Book("Il guerriero di Stonehenge","Mauro Raccasi",2026));
addBook(new Book("G. Paterniti","Asne Seierstad",2026));
addBook(new Book("Il libro della fotografia digitale vol.2","Scott Kelby",2026));
addBook(new Book("Il libro della fotografia digitale vol.3","Scott Kelby",2026));
addBook(new Book("Il libro della fotografia digitale Vol.1","Scott Kelby",2026));
addBook(new Book("G. P. Gasperi","Glenn Cooper",2026));
addBook(new Book("Latinoamericana","Ernesto Che Guevara",2026));
addBook(new Book("John Mitchinson","John Lloyd",2026));
addBook(new Book("James Gosling","Ken Arnold",2026));
addBook(new Book("Il medaglione","Andrea Camilleri",2026));
addBook(new Book("S. Bucchi","Gaetano Salvemini",2026));
addBook(new Book("Il muro del sorriso","Nino Taranto",2026));
addBook(new Book("Il nipote del Negus","Andrea Camilleri",2026));
addBook(new Book("Il nuovo disegnare con la parte destra del cervello","Betty Edwards",2026));
addBook(new Book("Il presente non basta. La lezione del latino","Ivano Dionigi",2026));
addBook(new Book("Il principe della nebbia","Carlos Ruiz Zafon",2026));
addBook(new Book("Il pugno di Dio","Frederick Forsyth",2026));
addBook(new Book("Il quinto figlio","Doris Lessing",2026));
addBook(new Book("Il re di Girgenti","Andrea Camilleri",2026));
addBook(new Book("Il respiro della savana","Tony Park",2026));
addBook(new Book("M. Bottini","Glenn Cooper",2026));
addBook(new Book("Il segreto dei geroglifici. Come entrare nel magico mondo degli antichi egizi","Christian Jacq",2026));
addBook(new Book("Il segreto di Cheope: Alla ricerca del tesoro perduto delle piramidi (I volti della storia) (Italian Edition)","Roberto Giacobbo",2026));
addBook(new Book("R. Rambelli","Wilbur Smith",2026));
addBook(new Book("A. Biavasco","Dan Brown",2026));
addBook(new Book("La scuola laica: Gaetano Salvemini contro i clericali","Gaetano Pecora",2026));
addBook(new Book("Il sistema della corruzione","Piercamillo Davigo",2026));
addBook(new Book("Il sogno e la sua interpretazione","Sigmund Freud",2026));
addBook(new Book("Il sonaglio","Andrea Camilleri",2026));
addBook(new Book("Il tailleur grigio","Andrea Camilleri",2026));
addBook(new Book("Il tesoro dell'abate Sauniére","Jean-Michel Thibaux",2026));
addBook(new Book("C. Melloni","Edward Luce",2026));
addBook(new Book("P. Lanterna","Michel Benoìt",2026));
addBook(new Book("M. Savini","Omero",2026));
addBook(new Book("Giovanni Spinicchia","Simone Casu",2026));
addBook(new Book("Imparare Perl in 24 ore. Con CD-ROM","Clinton Pierce",2026));
addBook(new Book("L. Tarlazzi","Alberto Angela",2026));
addBook(new Book("Impronte degli dei","Graham Hancock",2026));
addBook(new Book("In cerca di Klingsor","Jorge Volpi",2026));
addBook(new Book("L. Sanvito","Danila Comastri Montanari",2026));
addBook(new Book("Mauro Pesce","Corrado Augias",2026));
addBook(new Book("Jules Brown","Robert Andrews",2026));
addBook(new Book("Insciallah","Oriana Fallaci",2026));
addBook(new Book("S. Pedroni","John Peter Sloan",2026));
addBook(new Book("Intrigo italiano","Carlo Lucarelli",2026));
addBook(new Book("Introduzione a SQL","vuoto",2026));
addBook(new Book("Io sono Dio","Giorgio Faletti",2026));
addBook(new Book("Io uccido","Giorgio Faletti",2026));
addBook(new Book("Ireland: 700 Headwords (Oxford Bookworms Library)","Tim Vicary",2026));
addBook(new Book("Geoff Wallis","Margaret Greenwood",2026));
addBook(new Book("David Bradshaw","Aldous Huxley",2026));
addBook(new Book("J2EE","Aaron E. Walsh",2026));
addBook(new Book("JAVA 2","vuoto",2026));
addBook(new Book("Michael Morrison","Danny Goodman",2026));
addBook(new Book("JOOMLA","vuoto",2026));
addBook(new Book("Kenya","Sylvio Fresco",2026));
addBook(new Book("KEOPS IL ROMANZO DELLA PIRAMIDE (IL TESTAMENTO DEGLI DEI TRADUCCION DE PATRICIA CHENDI)","Christian Jacq",2026));
addBook(new Book("L' antico Egitto. Dagli albori della civiltà egiziana alla formazione del primo Impero","Manfred Clauss",2026));
addBook(new Book("L' uomo Mosè e la religione monoteistica","Sigmund Freud",2026));
addBook(new Book("L'India","Giancarlo De Cataldo",2026));
addBook(new Book("Screw it","Richard Branson",2026));
addBook(new Book("L. Rodin?","Lin Anderson",2026));
addBook(new Book("Il pensiero di Che Guevara","Ernesto Che Guevara",2026));
addBook(new Book("P. Bernardini","Hannah Arendt",2026));
addBook(new Book("La banda dei brocchi","Jonathan Coe",2026));
addBook(new Book("G. P. Gasperi","Glenn Cooper",2026));
addBook(new Book("Guarda caso: I meccanismi segreti del mondo quantistico","Giorgio Chinnici",2026));
addBook(new Book("La caccia al tesoro","Andrea Camilleri",2026));
addBook(new Book("Renzo Guidieri","Roland Barthes",2026));
addBook(new Book("La casa dei segreti","Gerri Brightwell",2026));
addBook(new Book("La Casa Del Sonno (Universale Economica) (Italian Edition)","Jonathan Coe",2026));
addBook(new Book("F. Maiello","Carlo Verdone",2026));
addBook(new Book("La cattedrale dei nove specchi. Parthenope trilogy","Martin Rua",2026));
addBook(new Book("La città eterna","Baldassarre Mancuso",2026));
addBook(new Book("La concessione del telefono","Andrea Camilleri",2026));
addBook(new Book("La cucina romana e del Lazio","Livio Jannattoni",2026));
addBook(new Book("La danza del gabbiano","Andrea Camilleri",2026));
addBook(new Book("La dieta Dukan","Pierre Dukan",2026));
addBook(new Book("La dinastia. Il romanzo dei cinque imperatori","Andrea Frediani",2026));
addBook(new Book("La distruzione dell'antica Roma. Lo scempio dei monumenti nel corso dei secoli","Rodolfo Lanciani",2026));
addBook(new Book("L. Polacco","Dante Alighieri",2026));
addBook(new Book("La Famiglia Winshaw (Universale Economica) (Italian Edition)","Jonathan Coe",2026));
addBook(new Book("La favola di Amore e Psiche. Testo latino a fronte","Apuleio",2026));
addBook(new Book("Folco Terzani","Tiziano Terzani",2026));
addBook(new Book("La forma dell'acqua","Andrea Camilleri",2026));
addBook(new Book("La Grande piramide e lo Zed : nuove scoperte nella piramide : come fu costruita e cosa nasconde","Mario Pincherle",2026));
addBook(new Book("La grande strategia dell'impero romano","Edward N. Luttwak",2026));
addBook(new Book("La legge del deserto","Wilbur Smith",2026));
addBook(new Book("M. E. Morin","Laurence Gardner",2026));
addBook(new Book("Tullio De Mauro","Andrea Camilleri",2026));
addBook(new Book("La locandiera","Carlo Goldoni",2026));
addBook(new Book("La luna di carta","Andrea Camilleri",2026));
addBook(new Book("La macchina imperfetta. Immagine e realtà dello Stato fascista","Guido Melis",2026));
addBook(new Book("Liliana Segre","Enrico Mentana",2026));
addBook(new Book("La Mennulara","Simonetta Agnello Hornby",2026));
addBook(new Book("Guido Cosenza","Giulietto Chiesa",2026));
addBook(new Book("La mossa del cavallo","Andrea Camilleri",2026));
addBook(new Book("D. Vogelmann","Elie Wiesel",2026));
addBook(new Book("La notte del Leopardo","Wilbur Smith",2026));
addBook(new Book("La notte della rabbia","Roberto Riccardi",2026));
addBook(new Book("La paura di Montalbano","Andrea Camilleri",2026));
addBook(new Book("La pioggia prima che cada","Jonathan Coe",2026));
addBook(new Book("La pista di sabbia","Andrea Camilleri",2026));
addBook(new Book("La Questione Meridionale","Antonio Gramsci",2026));
addBook(new Book("La Regina di Pomerania: E altre storie di Vigàta","Andrea Camilleri",2026));
addBook(new Book("La resistenza dei vinti. Percorsi nell'Africa contadina","Giordano Sivini",2026));
addBook(new Book("La rete di protezione","Andrea Camilleri",2026));
addBook(new Book("T. Rizzi","Irving Sloane",2026));
addBook(new Book("Clive Prince","Lynn Picknett",2026));
addBook(new Book("La rivoluzione delle tasse. Contro il partito degli evasori","Bruno Tinti",2026));
addBook(new Book("La rizzagliata","Andrea Camilleri",2026));
addBook(new Book("La schiavità del capitale","Luciano Canfora",2026));
addBook(new Book("La scomparsa dei fatti. Si prega di abolire le notizie per non disturbare le opinioni","Marco Travaglio",2026));
addBook(new Book("La Scomparsa di Majorana","Leonardo Sciascia",2026));
addBook(new Book("La Setta Degli Angeli","Andrea Camilleri",2026));
addBook(new Book("La solitudine dei numeri primi","Paolo Giordano",2026));
addBook(new Book("La spiaggia infuocata","Wilbur Smith",2026));
addBook(new Book("La Storia Vol.1 dalla preistoria agli Egizi","vuoto",2026));
addBook(new Book("La Strega di Portobello","Paulo Cohelo",2026));
addBook(new Book("La targa","Andrea Camilleri",2026));
addBook(new Book("La terza guerra mondiale? La verità sulle banche","Elido Fazi",2026));
addBook(new Book("E. Villa","Steve Berry",2026));
addBook(new Book("La vampa d'agosto","Andrea Camilleri",2026));
addBook(new Book("La Verita Del Ghiaccio","Dan Brown",2026));
addBook(new Book("La Verità Perduta","Tacconi",2026));
addBook(new Book("La voce del tuono","Wilbur Smith",2026));
addBook(new Book("Laboratorio di circuiti elettrici con OrCAD PSpice","Franz Monssen",2026));
addBook(new Book("L'affaire Moro (Piccola Biblioteca Adelphi)","Leonardo Sciascia",2026));
addBook(new Book("L'Amore ai Tempi del Colera","Gabriel Garcia Marquez",2026));
addBook(new Book("L'amore al tempo dei romani","Catherine Salles",2026));
addBook(new Book("Cecità","José Saramago",2026));
addBook(new Book("L'Archeologo","Arthur Phillips",2026));
addBook(new Book("L'Arte d'Amare","Ovidio",2026));
addBook(new Book("L'arte del colore. Guida pratica all'uso dei colori","Betty Edwards",2026));
addBook(new Book("Rob Sheppard","Art Wolfe",2026));
addBook(new Book("Latino","Nicola Gardini",2026));
addBook(new Book("Bruno Munari","Rinaldo Donzelli",2026));
addBook(new Book("L'avventura coloniale italiana. L'Africa Orientale Italiana (1885-1942)","Gianni Oliva",2026));
addBook(new Book("Le ali della sfinge","Andrea Camilleri",2026));
addBook(new Book("Le avventure di Sherlock Holmes","A.Conan Doyle",2026));
addBook(new Book("Le canzoni di Peter Gabriel","Davide Castellini",2026));
addBook(new Book("Le chiavi del disegno","Berto Dodson",2026));
addBook(new Book("Le inchieste del commissario Collura","Andrea Camilleri",2026));
addBook(new Book("Le meraviglie di Roma. Dal Rinascimento ai giorni nostri","Vittorio Sgarbi",2026));
addBook(new Book("A. Moro","Laurence Gardner",2026));
addBook(new Book("Le Nevi del Kilimangiaro / The Snows of Kilimanjaro [Bilingual Text]","Ernest Hemingway",2026));
addBook(new Book("Le nove chiavi dell'antiquario. Parthenope trilogy","Martin Rua",2026));
addBook(new Book("Le origini culturali del Terzo Reich","George L. Mosse",2026));
addBook(new Book("Le origini del fascismo in Italia","Gaetano Salvemini",2026));
addBook(new Book("Le pecore e il pastore","Andrea Camilleri",2026));
addBook(new Book("C. Marinelli","Javier Sierra",2026));
addBook(new Book("Le prime luci del mattino","Fabio Volo",2026));
addBook(new Book("Le radici dell'odio. La mia verità sull'Islam","Oriana Fallaci",2026));
addBook(new Book("Il concetto di Dio dopo Auschwitz","Hans Jonas",2026));
addBook(new Book("Le ricette della dieta Dukan. 350 ricette per dimagrire senza soffrire","Pierre Dukan",2026));
addBook(new Book("Le tre del mattino","Gianrico Carofiglio",2026));
addBook(new Book("L'economia buona","Emanuele Campiglio",2026));
addBook(new Book("L'Egitto dei grandi Faraoni","Christian Jacq",2026));
addBook(new Book("L'eleganza Del Riccio","Muriel Barberry",2026));
addBook(new Book("L'enigma del Bafometto","Pietro Borromeo",2026));
addBook(new Book("L'eros","Alberto Bevilacqua",2026));
addBook(new Book("L'Esclusa","Luigi. Pirandello",2026));
addBook(new Book("L'eskimo in redazione","Michele Brambilla",2026));
addBook(new Book("L'estate torbida","Carlo Lucarelli",2026));
addBook(new Book("Let It Bleed","Ian Rankin",2026));
addBook(new Book("L'eta del dubbio","Andrea Camilleri",2026));
addBook(new Book("Letteratura latina","Sabrina Torno",2026));
addBook(new Book("Traitors of the Tower","Allison Weir",2026));
addBook(new Book("M. Cescon","Vincent Van Gogh",2026));
addBook(new Book("P. Spriano","Antonio Gramsci",2026));
addBook(new Book("Cuire di Tenebra","Joseph Conrad",2026));
addBook(new Book("Lezione di fotografia. La natura delle fotografie","Stephen Shore",2026));
addBook(new Book("Libera scienza in libero Stato","Margherita Hack",2026));
addBook(new Book("Limit","Frank Schatzing",2026));
addBook(new Book("L'Insostenibile Leggerezza dell'essere","Milan Kundera",2026));
addBook(new Book("Linux cookbook","Carla Schroder",2026));
addBook(new Book("Linux Network Server","Craig Hunt",2026));
addBook(new Book("J. Bacon","Hill B. Mako",2026));
addBook(new Book("L'Isola della strage - Morte ai Caraibi","Jonathan Nasaw",2026));
addBook(new Book("Nujeen Mustafa","Christina Lamb",2026));
addBook(new Book("Lo Zahir","Paulo Coelho",2026));
addBook(new Book("L'occhio del Fotografo - La composizione nella fotografia digitale","Michael Freeman",2026));
addBook(new Book("L'occhio di Horus","Irene Belloni",2026));
addBook(new Book("L'ombra del Bafometto","Pietro Borromeo",2026));
addBook(new Book("L'ombra del sole","Wilbur Smith",2026));
addBook(new Book("L'ombra Del Vento","Carlos Ruiz Zafon",2026));
addBook(new Book("London","Edward Rutherfurd",2026));
addBook(new Book("London","Touring club italiano",2026));
addBook(new Book("London (Italian Edition)","Lonely Planet",2026));
addBook(new Book("Londra","vuoto",2026));
addBook(new Book("Londra","Rob Humphreys",2026));
addBook(new Book("E Marx tacque nel giardino di Darwin","Ilona Jerger",2026));
addBook(new Book("E. Filippini","Walter Benjamin",2026));
addBook(new Book("L'ordine del tempo","Carlo Rovelli",2026));
addBook(new Book("L'Origine Perduta","Matilde Asensi",2026));
addBook(new Book("L'uccello del sole","Wilbur Smith",2026));
addBook(new Book("L'Ultimo Catone","Matilde Asensi",2026));
addBook(new Book("Lussuria. Peccati","Emiliano Fittipaldi",2026));
addBook(new Book("Lyrics 1962-2001. Testo inglese a fronte","Bob Dylan",2026));
addBook(new Book("Ma liberaci dal male","Costantino D'Orazio",2026));
addBook(new Book("Maat","Christian Jacq",2026));
addBook(new Book("Mac OS X Leopard. Guida pocket","Chuck Toporek",2026));
addBook(new Book("Mammut","Antonio Pennacchi",2026));
addBook(new Book("Peter Gomez","Gianni Barbaceto",2026));
addBook(new Book("Manuale Cremonese di Elettrotecnica","Vari",2026));
addBook(new Book("Manuale Cremonese di MECCANICA","Vari",2026));
addBook(new Book("Manuale Cremonese di MECCANICA ELETTROTECNICA ELETTRONICA","Vari",2026));
addBook(new Book("Manuale Cremonese di MECCANINCA ELETTORTECNICA ELETTRONICA","Vari",2026));
addBook(new Book("Manuale del Perito in elettronica telecomunicazioni energia nucleare","Vari",2026));
addBook(new Book("Marina","Carlos Ruiz Zafon",2026));
addBook(new Book("Shaun McVeigh","Mark Ellingham",2026));
addBook(new Book("Martha Quest","Doris Lessing",2026));
addBook(new Book("Maruzza Musumeci","Andrea Camilleri",2026));
addBook(new Book("Massoni. Società a responsabilità illimitata. La scoperta delle Ur-Lodges","Magaldi Gioele",2026));
addBook(new Book("A. Peroni","Albrecht Beutelspacher",2026));
addBook(new Book("L. Storoni Mazzolani","Marguerite Yourcenar",2026));
addBook(new Book("Memorie di una principessa etiope","Martha Nasib?",2026));
addBook(new Book("The Master Switch","Tim Wu",2026));
addBook(new Book("Meno e meglio. Decrescere per progredire","Maurizio Pallante",2026));
addBook(new Book("Frank Z?llner","Thomas Thoenes",2026));
addBook(new Book("I. Vaj","Khaled Hosseini",2026));
addBook(new Book("Mindscapes. Psiche nel paesaggio","Vittorio Lingiardi",2026));
addBook(new Book("Monsone","Wilbur Smith",2026));
addBook(new Book("Morituri te salutant","Danila Comastri Montanari",2026));
addBook(new Book("Mors tua","Danila Comastri Montanari",2026));
addBook(new Book("Mortal Causes","Ian Rankin",2026));
addBook(new Book("Mussolini urbanista. Lo sventramento di Roma negli anni del consenso","Antonio Cederna",2026));
addBook(new Book("My SQL 5","Michael Kofler",2026));
addBook(new Book("MySQL","Bois Paul Du",2026));
addBook(new Book("Stefan Hinz","Paul DuBois",2026));
addBook(new Book("Derek J. Balling","Jeremy D. Zawodny",2026));
addBook(new Book("MySQL. Guida ufficiale","MySQL AB",2026));
addBook(new Book("Naples '44: A World War II Diary of Occupied Italy","Lewis",2026));
addBook(new Book("E. Martin","Boris Pahor",2026));
addBook(new Book("Nefer","Christin Jacq",2026));
addBook(new Book("Nei giardini d'acqua","Alan Drew",2026));
addBook(new Book("R. Serrai","Chris Offutt",2026));
addBook(new Book("Nemesis","Danila Comastri Montanari",2026));
addBook(new Book("Nero a meta'. Dalle origini a Grande madre tutta la poesia di Pino Daniele","Marcella Russano",2026));
addBook(new Book("NEW ENGLISH FILE INTERMEDIATE PACK WITHOUT KEY MULTIROM PACK (NEW ENGLISH FILE INTERMEDIATE PACK)","CHRISTINA LATHAM-KOENIG CLIVE OXENDEN",2026));
addBook(new Book("New Yorkers - Short Stories: 700 Headwords (Oxford Bookworms Library)","vari",2026));
addBook(new Book("Niente di vero tranne gli occhi","Giorgio Faletti",2026));
addBook(new Book("Niente e' come sembra. Con DVD","Franco Battiato",2026));
addBook(new Book("Nineteen Eighty-four","George Orwell",2026));
addBook(new Book("E. Giovannini","Carlo Conti",2026));
addBook(new Book("vuoto","vuoto",2026));
addBook(new Book("Non Ti Muovere","Margaret Mazzantini",2026));
addBook(new Book("Nonostante Auschwitz. Il ritorno del razzismo in Europa","Alberto Burgio",2026));
addBook(new Book("Nora","Carlo Tronchetti",2026));
addBook(new Book("Novelle dal Decameron","Giovanni Boccaccio",2026));
addBook(new Book("O Alquimista","Paulo Coelho",2026));
addBook(new Book("Odio gli indifferenti","Antonio Gramsci",2026));
addBook(new Book("Il grande Gatsby","Francis Scott Fitzgerald",2026));
addBook(new Book("Odissea. Ediz. integrale","Omero",2026));
addBook(new Book("Oliver Twist: 2500 Headwords (Oxford Bookworms Library)","Charles Dickens",2026));
addBook(new Book("On Chesil Beach","Ian McEwan",2026));
addBook(new Book("Opere narrative. Vol. 1","Marquez Gabriel Garcia",2026));
addBook(new Book("Opere narrative. Vol. 2","Marquez Gabriel Garcia",2026));
addBook(new Book("A. Prete","Giacomo Leopardi",2026));
addBook(new Book("Marlene Theriault","Kevin Loney",2026));
addBook(new Book("Oracle Database 10g Express Edition PHP Web Programming (Osborne ORACLE Press Series)","Michael McLaughlin",2026));
addBook(new Book("Oracle Database 10g. Amministrazione in Linux","Edward Whalen",2026));
addBook(new Book("Ron Hardman","Scott Hurman",2026));
addBook(new Book("Oracle Database 10g. SQL","Jason Price",2026));
addBook(new Book("Bradley D. Brown","Lawrence C. Linnemeyer",2026));
addBook(new Book("Orizzonte","Wilbur Smith",2026));
addBook(new Book("Orizzonte bianco. Scoperte scientifiche e avventura umana nella base italiana in Antartide","Marco Del Freo",2026));
addBook(new Book("Out of Africa (Penguin Modern Classics)","Karen Blixen",2026));
addBook(new Book("Sally Wehmeier","Albert Sydney Hornby",2026));
addBook(new Book("Angus Stevenson","Catherine Soanes",2026));
addBook(new Book("OXFORD STUDY per studenti d'inglese","vuoto",2026));
addBook(new Book("Painted Veil","WilliamSomerse Maugham",2026));
addBook(new Book("Palude","Antonio Pennacchi",2026));
addBook(new Book("Paneb","Christin Jacq",2026));
addBook(new Book("Pape Satan Aleppe: Cronache di una società liquida","Umberto Eco",2026));
addBook(new Book("Parce sepulto","Danila Comastri Montanari",2026));
addBook(new Book("Renzo De Felice","Paolo Puntoni",2026));
addBook(new Book("stefano disegni","Giobbe Covatta",2026));
addBook(new Book("Pasta madre. Tutto ciò che devi sapere per produrla","Roberta Ferraris",2026));
addBook(new Book("Andrea Guidi","Alessandro Bellini",2026));
addBook(new Book("Photoshop CS","Marisa Padovani",2026));
addBook(new Book("Photoshop CS5 per la fotografia digitale","Scott Kelby",2026));
addBook(new Book("Stig Bakken","Andi Gutmans",2026));
addBook(new Book("PHP 5. Guida per lo sviluppatore","vuoto",2026));
addBook(new Book("Picture Her Dead (Rhona MacLeod)","Lin Anderson",2026));
addBook(new Book("Pompei. L'incubo e il risveglio","Angelo Petrella",2026));
addBook(new Book("Portico d'Ottavia n. 13. Una casa del ghetto nel lungo inverno del '43","Anna Foa",2026));
addBook(new Book("Practical Mono (Expert's Voice in Open Source)","Mark Mamone",2026));
addBook(new Book("Pride and Prejudice: 2500 Headwords (Oxford Bookworms Library)","Jane Austen",2026));
addBook(new Book("M. Grosso","Bart D. Ehrman",2026));
addBook(new Book("Professione: fotografo","John Ingledew",2026));
addBook(new Book("David Asher","Mark Lutz",2026));
addBook(new Book("Progressive & Underground","Cesare Rizzi",2026));
addBook(new Book("Psicoanalisi dell'amore","Erich Fromm",2026));
addBook(new Book("Pulvis et umbra","Antonio Manzini",2026));
addBook(new Book("Python","Marco Beri",2026));
addBook(new Book("Quando vola il falco","Wilbur Smith",2026));
addBook(new Book("M. G. Griffini","Agatha Christie",2026));
addBook(new Book("Racconti","Hermann Hesse",2026));
addBook(new Book("Racconti","Franz Kafka",2026));
addBook(new Book("Racconti africani","Doris Lessing",2026));
addBook(new Book("Racconti Londinesi","Doris Lessing",2026));
addBook(new Book("Ramesses II Il Grande","Franco Cimmino",2026));
addBook(new Book("Ramses 4 Regina DI Abu Simbel (Italian Edition)","vuoto",2026));
addBook(new Book("Ramses o Dimora Millenaria (Italian Edition)","vuoto",2026));
addBook(new Book("Ramses: L'ultimo nemico","Christian Jacq",2026));
addBook(new Book("Peter Gomez","Marco Travaglio",2026));
addBook(new Book("Reti di Computer","Andrews Tanenbaum",2026));
addBook(new Book("M. Cupellaro","Zygmunt Bauman",2026));
addBook(new Book("Rhinoceros. Guida all'uso","Roberto Fanchini",2026));
addBook(new Book("Mimmo Paladino","Costantino D'Orazio",2026));
addBook(new Book("Roma fascista: Nelle fotografie dell'Istituto Luce (L'immagine e la storia)","Italo Insolera",2026));
addBook(new Book("Adriano Morabito","Ginevra Lovatelli",2026));
addBook(new Book("Romolo. L'alba di Roma da riscrivere","Mario Sconcerti",2026));
addBook(new Book("Running Man","Stephen King",2026));
addBook(new Book("San Pietro. Segreti e meraviglie in un racconto lungo duemila anni","Alberto Angela",2026));
addBook(new Book("Saturnalia","Danila Comastri Montanari",2026));
addBook(new Book("Scelera","Danila Comastri Montanari",2026));
addBook(new Book("Donald Reid","Rob Humphreys",2026));
addBook(new Book("Scozia","300.000. Ediz. multilingue",2026));
addBook(new Book("Se il Sole Muore","Oriana Fallaci",2026));
addBook(new Book("Marco Travaglio","Peter Gomez",2026));
addBook(new Book("Sean Connery: Neither Shaken nor Stirred","Andrew Yule",2026));
addBook(new Book("Seasons and Celebrations (Oxford Bookworms Library)","Jackie Maguire",2026));
addBook(new Book("Sebastiao Salgado. Genesis","Lilla Salgado",2026));
addBook(new Book("Sei Personaggi in Cerca d'Autore / Enrico IV (Italian Edition)","Luigi Pirandello",2026));
addBook(new Book("Dan Behman","Mark Wilding",2026));
addBook(new Book("Sessanta Racconti","Dino Buzzati",2026));
addBook(new Book("Sessualità e vita amorosa","Sigmund Freud",2026));
addBook(new Book("Sette brevi lezioni di fisica","Carlo Rovelli",2026));
addBook(new Book("Sherlock Holmes Short Stories: 700 Headwords (Oxford Bookworms Library)","Sir Arthur Conan Doyle",2026));
addBook(new Book("Siddharta","Hermann Hesse",2026));
addBook(new Book("Shamkant B. Navathe","Ramez A. Elmasri",2026));
addBook(new Book("Slightly Out of Focus (Modern Library War)","Robert Capa",2026));
addBook(new Book("Socrate","Luciano De Crescenzo",2026));
addBook(new Book("Sonetti","Giuseppe Gioachino Belli",2026));
addBook(new Book("Spes","Danila Comastri Montanari",2026));
addBook(new Book("Spice e PSpice. Introduzione all'uso","Mario Biey",2026));
addBook(new Book("A. Piccato","Mary Beard",2026));
addBook(new Book("Storia della libertà di pensiero","Paolo Villaggio",2026));
addBook(new Book("Storia delle Piramidi","Franco Cimmino",2026));
addBook(new Book("Storia dell'Italia repubblicana (1946-1991)","Silvio Lanaro",2026));
addBook(new Book("Storia di Roma","Indro Montanelli",2026));
addBook(new Book("Storie. Testo greco a fronte. Vol. 1: Libri I-IV.","Erodoto",2026));
addBook(new Book("M. Villa","David Gibson",2026));
addBook(new Book("Strip Jack","Ian Rankin",2026));
addBook(new Book("S. Bucchi","Gaetano Salvemini",2026));
addBook(new Book("Ettore Capriolo","Susan Sontag",2026));
addBook(new Book("Sulla razza. Testo inglese a fronte","Barack Obama",2026));
addBook(new Book("Sulla rotta degli squali","Wilbur Smith",2026));
addBook(new Book("Bruna Bianchi","Hermann Hesse",2026));
addBook(new Book("Paola Sorge","Hermann Hesse",2026));
addBook(new Book("Sviluppo Web con XML e PHP","Thomas Myer",2026));
addBook(new Book("Tanzania","Jens Finke",2026));
addBook(new Book("G. Melchiori","William Shakespeare",2026));
addBook(new Book("Terreno di Gioco","Thomas Sanders",2026));
addBook(new Book("Testi religiosi dell'antico Egitto","vuoto",2026));
addBook(new Book("The Argyll Book","Donald Omand",2026));
addBook(new Book("The Artist's Complete Guide to Figure Drawing: A Contemporary Perspective On the Classical Tradition","Anthony Ryder",2026));
addBook(new Book("The Casual Vacancy","J.K. Rowling",2026));
addBook(new Book("The Cuckoo's Calling","Robert Galbraith",2026));
addBook(new Book("Stephen Hawking","Leonard Mlodinow",2026));
addBook(new Book("The Hound of the Baskervilles (Penguin Popular Classics)","Sir Arthur Conan Doyle",2026));
addBook(new Book("The House of Sleep","Jonathan Coe",2026));
addBook(new Book("Peter Conradi","Mark Logue",2026));
addBook(new Book("The Kite Runner","Khaled Hosseini",2026));
addBook(new Book("The Land of Osiris","Stephen S. Mehler",2026));
addBook(new Book("The Lost Child of Philomena Lee","Martin Sixsmith",2026));
addBook(new Book("The memories of Sherlock Holmes","Doyle Arthur Conan",2026));
addBook(new Book("The Mystery of the Blue Train (Hercule Poirot Mysteries)","Agatha Christie",2026));
addBook(new Book("The Negative (Ansel Adams Photography","Ansel Adams",2026));
addBook(new Book("The Print (Ansel Adams Photography","Ansel Adams",2026));
addBook(new Book("The Rain Before It Falls","Jonathan Coe",2026));
addBook(new Book("The Reborn: Rhona Macleod Book 7 (Rhona Macleod 7)","Lin Anderson",2026));
addBook(new Book("The returned","Jason Mott",2026));
addBook(new Book("The Revenge of Analog: Real Things and Why They Matter","David Sax",2026));
addBook(new Book("The Silkworm (Cormoran Strike)","Robert Galbraith",2026));
addBook(new Book("The Story of Scotland","Nigel Tranter",2026));
addBook(new Book("The Terrible Privacy of Maxwell Sim","Jonathan Coe",2026));
addBook(new Book("The Warmth of Other Suns: The Epic Story of America's Great Migration (Vintage)","Isabel Wilkerson",2026));
addBook(new Book("The woman in black (La donna in nero)","Susan Hill",2026));
addBook(new Book("Three Men in a Boat","Jerome Kapla Jerome",2026));
addBook(new Book("Ti Prendo E Ti Porto Via","Niccolo Ammaniti",2026));
addBook(new Book("Tooth & Nail","Ian Rankin",2026));
addBook(new Book("L'armadio della vergogna","Franco Giustolisi",2026));
addBook(new Book("Torch (Rhona MacLeod)","Lin Anderson",2026));
addBook(new Book("Trattato dei tre impostori. Mosè","Baruch Spinoza",2026));
addBook(new Book("True at First Light","Ernest  Hemingway",2026));
addBook(new Book("Tutorial Java. Corso rapido. Con CD-ROM","Isaac Rabinovitch",2026));
addBook(new Book("Tutte le barzellette su Totti : raccolte da me","Francesco Totti",2026));
addBook(new Book("The sleeping and the dead","Ann Cleeves",2026));
addBook(new Book("P. Mioli","Giuseppe Verdi",2026));
addBook(new Book("Tutti i poveri devono morire","Giovanni Di Iacovo",2026));
addBook(new Book("D. Palladini","Edgar Allan Poe",2026));
addBook(new Book("Tutti i romanzi. Vol. 1","Luigi Pirandello",2026));
addBook(new Book("Tutti i romanzi. Vol. 2","Luigi Pirandello",2026));
addBook(new Book("U2. Tutti i testi con traduzione a fronte","U2",2026));
addBook(new Book("Uccelli da preda","Wilbur Smith",2026));
addBook(new Book("Un filo di fumo","Andrea Camilleri",2026));
addBook(new Book("Un italiano vero. La lingua in cui viviamo","Giuseppe Antonelli",2026));
addBook(new Book("Un Matrimonio per Bene (Universale Economica Feltrinelli)","Doris Lessing",2026));
addBook(new Book("Una giornata nell'antica Roma. Vita quotidiana","Alberto Angela",2026));
addBook(new Book("Una Lama Di Luce","Andrea Camilleri",2026));
addBook(new Book("Un'aquila nel cielo","Wilbur Smith",2026));
addBook(new Book("Vendetta di sangue","Wilbur Smith",2026));
addBook(new Book("Venuto Al Mondo","Margaret Mazzantini",2026));
addBook(new Book("Verdi colline d'Africa","Ernest Hemingway",2026));
addBook(new Book("Via delle Oche","Carlo Lucarelli",2026));
addBook(new Book("Victoriana. Maschere e miti","Franco Pezzini",2026));
addBook(new Book("Vini d'Italia 2011","vuoto",2026));
addBook(new Book("Visual Basic 6","Francesco Balena",2026));
addBook(new Book("E. Castellani","Bertolt Brecht",2026));
addBook(new Book("Viva il latino. Storie e bellezza di una lingua inutile","Nicola Gardini",2026));
addBook(new Book("Voi non sapete. Gli amici","Andrea Camilleri",2026));
addBook(new Book("I racconti di Nenè","Andrea Camilleri",2026));
addBook(new Book("Gramsci per la scuola","Giuseppe Benedetti / Doantella Coccoli",2026));
addBook(new Book("Il dentista di Auschwitz","Benjamin Jacobs",2026));
addBook(new Book("La storia dell'arte","Flavio Caroli",2026));
addBook(new Book("Too good to be true","Ann Cleeves",2026));
addBook(new Book("Il Puzzle Moro","Giovanni Fasanella",2026));
addBook(new Book("Il metodo Catalanotti","Andrea Camilleri",2026));
addBook(new Book("Il silenzio delle pietre","Vittorino Andreoli",2026));
addBook(new Book("La svastica sul sole","Philip  K. Dick",2026));
addBook(new Book("L'Honda anomala","Pietro Ratto",2026));
addBook(new Book("Gli anni della vergogna 1938-1945","Amedeo Osti Guerrazzi",2026));
addBook(new Book("Istruzioni per diventare fascisti","Michela Murgia",2026));
addBook(new Book("Fater il vostro gioco","Antonio Manzini",2026));
addBook(new Book("Il regno di Acilia","Marco Baliani",2026));
addBook(new Book("O melhor das Comedias da Vida Privada","Luis Fernando Verissimo",2026));
addBook(new Book("Il complesso d'inferiorità","Enrico Mattei",2026));
addBook(new Book("Fed Factor","Mark Saborn",2026));
addBook(new Book("Dizionario LATINO","AAVV",2026));
addBook(new Book("Jeff Parker","Jessey Bullock",2026));
addBook(new Book("Diario","Anna Frank",2026));
addBook(new Book("El especialista de Barcelona","Aldo Busi",2026));
addBook(new Book("Pilgrim Spy","Tom Shore",2026));
addBook(new Book("Un campo di concentramento fascista","Alessandra Kersevan",2026));
addBook(new Book("Il fascismo degli antifascisti","Pier Paolo Pasolini",2026));
addBook(new Book("Watchman","Ian Rankin",2026));
addBook(new Book("We will rock you. Segreti e bugie. 709 canzoni come non le avete mai sentite","Massimo Cotto",2026));
addBook(new Book("Il ritorno degli dei","Graham Hancock",2026));
addBook(new Book("Web Design Index","Gunter Beer",2026));
addBook(new Book("What a Carve Up!","Jonathan Coe",2026));
addBook(new Book("David Hosking","Martin B. Withers",2026));
addBook(new Book("Windows Command line. Guida pratica","William R. Stanek",2026));
addBook(new Book("Zanzibar","Jens Finke",2026));
addBook(new Book("Arcipelago Gulag","Aleksandr Isaevic  Solzenicyn",2026));
addBook(new Book("Grand Tour d'Italia a piccoli passi","Philippe Daverio",2026));
addBook(new Book("Vita liquida","Zygmunt Bauman",2026));
addBook(new Book("Amore liquido","Zygmunt Bauman",2026));
addBook(new Book("Di nuovo soli","Zygmunt Bauman",2026));
addBook(new Book("1001 Fotografie da vedere nella vita","Paul Lowe",2026));
addBook(new Book("La Matrix Europea","Francesco Amodeo",2026));
addBook(new Book("Rien ne va plus","Antonio Manzini",2026));
addBook(new Book("Marco Palla","Paolo Giovannini",2026));
addBook(new Book("Elogio della Follia","Erasmo da Rotterdam",2026));
addBook(new Book("Il giovane Holden","J. D. Salinger",2026));
addBook(new Book("La Repubblica","Platone",2026));
addBook(new Book("Lettera sulla felicità","Epicuro",2026));
addBook(new Book("Fake news","Giuseppe Riva",2026));
addBook(new Book("Hitler","Ian Kershaw",2026));
addBook(new Book("Telling tales","Ann Cleeves",2026));
addBook(new Book("Libro Verde","Muammar Gheddafi",2026));
addBook(new Book("Incidente em Antares","Erico Verissimo",2026));
addBook(new Book("Appia","Paolo Rumiz",2026));
addBook(new Book("La guerra gallica","Caio Giulio Cesare",2026));
addBook(new Book("Poetica","Aristotele",2026));
addBook(new Book("Colestdrolo tutta la verità","Philippe Even",2026));
addBook(new Book("La verità sul colesterolo","Barbara H. Roberts",2026));
addBook(new Book("La mente inquieta","Massimo Cacciari",2026));
addBook(new Book("DANTE - una vita in esilio","Chiara Mercuri",2026));
addBook(new Book("Etiopia - il cuore antico dell'Africa","Massimo Bacale - Piera Borghetti",2026));
addBook(new Book("Lessico essenziale di Latino","Francesco Piazzi",2026));
addBook(new Book("Leonardo da Vinci - The Graphic Work","Johannes Nathan - Frank Zoller",2026));
addBook(new Book("La Storia dell'Arte","E. H. Gombrich",2026));
addBook(new Book("Renoir","Gilles Neret",2026));
addBook(new Book("Sapiens","Yuval Noah Harari",2026));
addBook(new Book("Gli italiani in Libia - dal fascismo a Gheddafi","Angelo del Boca",2026));
addBook(new Book("Gli italiani in Libia 1860-1922","Angelo del Boca",2026));
addBook(new Book("De Umbris Idearum","Giordano Bruno",2026));
addBook(new Book("Migrazioni e intolleranza","Umberto Eco",2026));
addBook(new Book("Dai Fascismi ai Populismi","Federico Finchelstein",2026));
addBook(new Book("Non dirmi che hai paura","Giuseppe Catozzella",2026));
addBook(new Book("Cristo si è fermato a Eboli","Carlo Levi",2026));
addBook(new Book("Ventuno giorni per rinascere","Franco Berrino",2026));
addBook(new Book("L'arte dell'hacking","Jon Erickson",2026));
addBook(new Book("Python per hacker","Justin Seitz",2026));
addBook(new Book("Le Reti","Peter Norton",2026));
addBook(new Book("The Linux Network","Fred Butzen",2026));
addBook(new Book("NMAP Network Scanning","Gordon Fyodor Lyon",2026));
addBook(new Book("Hacker 7.0","Stuart McClure",2026));
addBook(new Book("Programmare con Python","Marco Buttu",2026));
addBook(new Book("Leviatano","Thomas Hobbes",2026));
addBook(new Book("Linux How To","PLUTO Linux User Group",2026));
addBook(new Book("Slackware Linux 7","Joe Brockmeier",2026));
addBook(new Book("MySQL5 Guida Completa","Michael Kofler",2026));
addBook(new Book("Rosita Rijitano","Alessandro Vespignani",2026));
addBook(new Book("Fuoco è tutto ciò che siamo","Guido Saraceni",2026));
addBook(new Book("Il filo infinito","Paolo Rumiz",2026));
addBook(new Book("Documenti","Andrea Vitali",2026));
addBook(new Book("Il mio nome è nessuno","Valerio Massimo Manfredi",2026));
addBook(new Book("Sicilia","vari",2026));
addBook(new Book("Il cuoco dell'Alcyon","Andrea Camilleri",2026));
addBook(new Book("Ognuno muore solo","Hans Fallada",2026));
addBook(new Book("La nascita della filosofia","Giorgio Colli",2026));
addBook(new Book("L'interprete","Annette Hess",2026));
addBook(new Book("Se non ora","Primo Levi",2026));
addBook(new Book("I sommersi e i salvati","Primo Levi",2026));
addBook(new Book("La tregua","Primo Levi",2026));
addBook(new Book("Il sistema periodico","Primo Levi",2026));
addBook(new Book("La chiave a stella","Primo Levi",2026));
addBook(new Book("Nella Notte","Concita De Gregorio",2026));
addBook(new Book("C guida tascabile","H. Schildt",2026));
addBook(new Book("Python","Marco Beri",2026));
addBook(new Book("Linux guida pratica","Michel Stutz",2026));
addBook(new Book("La Cripta dei Cappuccini","Joseph Roth",2026));
addBook(new Book("No Picnic On Mount Kenya","Felice Benuzzi",2026));
addBook(new Book("Barbarie","Cacciari ++",2026));
addBook(new Book("Sandra Rizza","Giuseppe Lo Bianco",2026));
addBook(new Book("Il sistema montante","Salvatore Petrotto",2026));
addBook(new Book("Viaggio in Sicilia","Johann Wolgang Goethe",2026));
addBook(new Book("Federico II e il suo tempo","Vari",2026));
addBook(new Book("Il libro che cambierà per sempre le nostre idee sulla bibbia","Mauro Biglino",2026));
addBook(new Book("La Bibbia non parla di Dio","Mauro Biglino",2026));
addBook(new Book("Decameron","Giovanni Boccaccio",2026));
addBook(new Book("My Purple Scented Novel","Ian McEwan",2026));
addBook(new Book("Machines like me","Ian McEwan",2026));
addBook(new Book("De Senectute De Amicitia","Cicerone",2026));
addBook(new Book("La grande guida dei monumenti di Roma","Claudio Rendina",2026));
addBook(new Book("Guida insolita di Roma","Claudio Rendina",2026));
addBook(new Book("Nazionalisti e Patrioti","Maurizio Viroli",2026));
addBook(new Book("Francesco d'Assisi","Chiara Mercuri",2026));
addBook(new Book("Democrazia Totalitaria","Alessandro Mulieri",2026));
addBook(new Book("La progettazione dei circuiti amplificaori operazionali","Howard M. Berlin",2026));
addBook(new Book("La progettazione dei filtri attivi","Howard M. Berlin",2026));
addBook(new Book("Assassinio a Villa Borghese","Walter Veltroni",2026));
addBook(new Book("Storia di Roma","Indro Montanelli",2026));
addBook(new Book("Microbiota Intestinale","Luciano Lozio",2026));
addBook(new Book("Le religioni sono vie di pace","Paolo Naso",2026));
addBook(new Book("Errore di sistema","Edward Snowen",2026));
addBook(new Book("Come difendersi dai Romani","Elena Pigozzi",2026));
addBook(new Book("Miracolo e Suicidio dell'Occidente","Jonah Goldberg",2026));
addBook(new Book("Modo di legare i libri","Fabio Cusimano",2026));
addBook(new Book("Wikibolario","Zap e Ida",2026));
addBook(new Book("Autodifesa di Caino","Andrea Camilleri",2026));
addBook(new Book("Una Vita","Italo Svevo",2026));
addBook(new Book("La Coscienza di Zeno","Italo Svevo",2026));
addBook(new Book("Senilità","Italo Svevo",2026));
addBook(new Book("Christine Coste","Guillaume Sorel",2026));
addBook(new Book("Praga","Michelin",2026));
addBook(new Book("Samburu","Nigel Pavitt",2026));
addBook(new Book("Aldo Chietera","Mariavittoria Carnovale",2026));
addBook(new Book("Il Cimitero Acattolico di Roma","Johan Beck-Friis",2026));
addBook(new Book("Cinque Terre e Porto Venere","Gino Montefinale",2026));
addBook(new Book("Chingula e altre storie","Vari",2026));
addBook(new Book("Poeti Africani Anti Apartheid","Vari",2026));
addBook(new Book("Francesco Ticca","Salvatore Colombo",2026));
addBook(new Book("Piatti Unici 500 ricette","Laura Rangoni",2026));
addBook(new Book("Museo Egizio di Torino","Alessandro Roccati",2026));
addBook(new Book("Cinzia Rando","Elena Luraghi",2026));
addBook(new Book("Elba tutte le spiagge","Vari",2026));
addBook(new Book("Rosslyn Chapel","Vari",2026));
addBook(new Book("Il Castello di Edimburgo","Vari",2026));
addBook(new Book("The Burrel Collection","Vari",2026));
addBook(new Book("Dizionario dell'Opera 2008","Piero Gelli",2026));
addBook(new Book("Brasile","Vari",2026));
addBook(new Book("Mattia Brambilla","Marco Gustin",2026));
addBook(new Book("Il Ghetto di Roma","Francesco Sinagra",2026));
addBook(new Book("Siena","Vari",2026));
addBook(new Book("Osterie d'Italia 2020","Vari",2026));
addBook(new Book("I Borghi più belli d'Italia","Vari",2026));
addBook(new Book("Il Libro di Tutti i Libri","Roberto Calasso",2026));
addBook(new Book("Il Ritratto Perfetto","Chris Knight",2026));
addBook(new Book("Giovanni Filoramo","Corrado Augias",2026));
addBook(new Book("L'Architettrice","Melania Gaia Mazzucco",2026));
addBook(new Book("La Profezia di Celestino","James Redfield",2026));
addBook(new Book("Homo Deus","Yuval Noah Harari",2026));
addBook(new Book("Come insultavano gli antichi Romani","Vari",2026));
addBook(new Book("Antica Madre","Valerio Massimo Manfredi",2026));
addBook(new Book("21 Lezioni per il XXI Secolo","Yuval Noah Harari",2026));
addBook(new Book("Le 999 donne di Auschwitz","Heather Dune Macadam",2026));
addBook(new Book("Al Vento dell'Oceano","Hans Tuzzi",2026));
addBook(new Book("Analisi statistica dei dati con R","Franco Crivellari",2026));
addBook(new Book("The Eyes of Darkness","Dean Koontz",2026));
addBook(new Book("Il Vaticano Nella Tormenta","Cesare Catananti",2026));
addBook(new Book("La Peste","Albert Camus",2026));
addBook(new Book("Italia Longobarda","Stefano Gasparri",2026));
addBook(new Book("IL DIO DI UNA ESTATE","Ralf Rothmann",2026));
addBook(new Book("I Vicerè","Federico De Roberto",2026));
addBook(new Book("Il Paradosso della Bontà","Richard Wrangham",2026));
addBook(new Book("Parole di scuola","Mariapia Veladiano",2026));
addBook(new Book("Epuloni e Lazzari","Cosmo Giacomo Sallustio Salvemini",2026));
addBook(new Book("Mussolini ha fatto anche cose buone","Francesco Filippi",2026));
addBook(new Book("Perchè parlavo da solo","Paolo Bonolis",2026));
addBook(new Book("I Leoni Di Sicila","Stefania Auci",2026));
addBook(new Book("Manuale di disobbedienza digitale","Nicola Zamperini",2026));
addBook(new Book("Come la Chiesa finì","Aldo Maria Valli",2026));
addBook(new Book("Il buonuomo Lenin","Curzio Malaparte",2026));
addBook(new Book("Homo Premium","Massimo Gaggi",2026));
addBook(new Book("La sinistra che verrà","Giuliano Battiston",2026));
addBook(new Book("Vivere 120 anni: Le Ricette","Adriano Panzironi",2026));
addBook(new Book("Vivere 120 anni","Adriano Panzironi",2026));
addBook(new Book("Le Consolazioni","Seneca",2026));
addBook(new Book("Menschen A1.1 kursbuch","Sandra Evans",2026));
addBook(new Book("Menschen A1.1 arbeitsbuch","Sandra Evans",2026));
addBook(new Book("DEUTSCHE GRAMMATIK FUR ITALIENER","Hans Scollo",2026));
addBook(new Book("R. Micciolo","G. Espa",2026));
addBook(new Book("Finalmente ho capito la Statistica","Maurizio De Pra",2026));
addBook(new Book("3250 Acordes para violao","Fernando Azervedo",2026));
addBook(new Book("Quality Land per ottimisti","Marc-Uwe Kling",2026));
addBook(new Book("L'Animale Morente","Philip Roth",2026));
addBook(new Book("Everyman","Philip Roth",2026));
addBook(new Book("Il Tedesco Smart","Luisa Giacoma - Susanne Kolb",2026));
addBook(new Book("La tranquillità dell'anima","Seneca",2026));
addBook(new Book("Ah l'amore l'amore","Antonio Manzini",2026));
addBook(new Book("Il contrario di uno","Erri De Luca",2026));
addBook(new Book("Idi di Marzo","Valerio Massimo Manfredi",2026));
addBook(new Book("Breviario per un confuso presente","Corrado Augias",2026));
addBook(new Book("L'Inventore di sogni","Ian McEwan",2026));
addBook(new Book("Riccardino","Andrea Camilleri",2026));
addBook(new Book("Gente di Dublino","James Joyce",2026));
addBook(new Book("Il tallone di ferro","Jack London",2026));
addBook(new Book("Il vagabondo delle stelle","Jack London",2026));
addBook(new Book("Il popolo dell'abisso","Jack London",2026));
addBook(new Book("Sull'orlo del precipizio","Antonio Manzini",2026));
addBook(new Book("Adam Retter","Erik Siegel",2026));
addBook(new Book("Una Sola Moltitudine vol.1","Fernando Pessoa",2026));
addBook(new Book("La danza del gabbiano","Andrea Camilleri",2026));
addBook(new Book("La caccia al tesoro","Andrea Camilleri",2026));
addBook(new Book("Guerre in Gallia","Giulio Cesare",2026));
addBook(new Book("Sulla Felicità","Seneca",2026));
addBook(new Book("Teoria Generale dell'occupazione","John Maynard Keynes",2026));
addBook(new Book("L'Angelo di Monaco","Fabiano Massimi",2026));
addBook(new Book("La Peste Scarlatta","Jack London",2026));
addBook(new Book("Le sette morti dei Evelyn Headcastle","Stuart Turton",2026));
addBook(new Book("Cambiare l'acqua ai fiori","Valérie Perrin",2026));
addBook(new Book("L'educazione di un fascista","Paolo Berizzi",2026));
addBook(new Book("Aspetti del nuovo radicalismo di destra","Theodor W. Adorno",2026));
addBook(new Book("Ma perchè siamo ancora fascisti?","Francesco Filippi",2026));
addBook(new Book("M. Il figlio del secolo","Antonio Scurati",2026));
addBook(new Book("Vita di Gesù","Ernest Renan",2026));
addBook(new Book("L'Uomo è antiquato - 1","Gunther Anders",2026));
addBook(new Book("Trattato teologico-politico","Baruch Spinoza",2026));
addBook(new Book("Noi figli di Eichmann","Gunther Anders",2026));
addBook(new Book("Costruire il nemico","Umberto Eco",2026));
addBook(new Book("Il segreto del mercante di libri","Marcello Simoni",2026));
addBook(new Book("Gli archivi segreti della sezione M - V","Carlo Alberto Orlandi",2026));
addBook(new Book("La tentazione del muro","Massimo Recalcati",2026));
addBook(new Book("Il gesto di Caino","Massimo Recalcati",2026));
addBook(new Book("Too much and Never Enough","Mary L. Trump",2026));
addBook(new Book("Gli ultimi giorni di quiete","Antonio Manzini",2026));
addBook(new Book("Io ti cercherò","Massimo Bavastro",2026));
addBook(new Book("Fu sera e fu mattina","Ken Follet",2026));
addBook(new Book("Buonvino e il caso del bambino scomparso","Walter Veltroni",2026));
addBook(new Book("Anthony Zambonini","IELTS manuale di preparazione",2026));
addBook(new Book("P.Italia","G.Alfano",2026));
addBook(new Book("Broken Music","Sting",2026));
addBook(new Book("Dispositivi e circuiti elettronici Vol.1","Gasparini - Mirri",2026));
addBook(new Book("Dispositivi e circuiti elettronici Vol.2","Gasparini - Mirri",2026));
addBook(new Book("La patente da Radioamatore","Franco Malenza",2026));
addBook(new Book("The BeOS Bible","Scott Hacker",2026));
addBook(new Book("Schemario Kit 1990","Nuova Elettronica",2026));
addBook(new Book("The spectrum Guide to Kenya","Camerapix",2026));
addBook(new Book("Quaranta giorni","Valerio Massimo Manfredi",2026));
addBook(new Book("P.Italia","G.Alfano",2026));
addBook(new Book("Quattro conversazioni sull'Europa","Philippe Daverio",2026));
addBook(new Book("Storia della Repubblica Sociale Italiana","Mimmo Franzinelli",2026));
addBook(new Book("Helgoland","Carlo Rovelli",2026));
addBook(new Book("Cina Covid-19","Joseph Tritto",2026));
addBook(new Book("I Conquistatori","Lannutti E. Alterio T. Fracasso F.",2026));
addBook(new Book("T. Alterio","F. Fracassi",2026));
addBook(new Book("La Guerra Silenziosa","Tiziana Alterio",2026));
addBook(new Book("La generazione del deserto","Lia Tagliacozzo",2026));
addBook(new Book("Ritorniamo a sognare","Papa Francesco",2026));
addBook(new Book("Come ordinare una biblioteca","Roberto Calasso",2026));
addBook(new Book("Notre-Dame de Paris","Victor Hugo",2026));
addBook(new Book("Mussolini diplomatico","Gaetano Salvemini",2026));
addBook(new Book("I miti del nostri tempo","Umberto Galimberti",2026));
addBook(new Book("L'ospite inquietante","Umberto Galimberti",2026));
addBook(new Book("I Miserabili Vol. 1","Victor Hugo",2026));
addBook(new Book("I Miserabili Vol. 2","Victor Hugo",2026));
addBook(new Book("Liberalismo","Friederich A. von Hayek",2026));
addBook(new Book("Rondini d'Inverno","Maurizio De Giovanni",2026));
addBook(new Book("Il purgatorio dell'angelo","Maurizio De Giovanni",2026));
addBook(new Book("Quando abbiamo smesso di capire il mondo","Benjamin Labatut",2026));
addBook(new Book("Dante","Alessandro Barbero",2026));
addBook(new Book("Vita Nuova","Dante Alighieri",2026));
addBook(new Book("The Railway Man","Eric Lomax",2026));
addBook(new Book("La Divina Commedia","Dante Alighieri",2026));
addBook(new Book("Alabama","Alessandro Barbero",2026));
addBook(new Book("La Pensione Eva","Andrea Camilleri",2026));

}